apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${K8S_RESOURCE_NAME}
  namespace: dev
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      workload.user.cattle.io/workloadselector: apps.deployment-dev-${K8S_RESOURCE_NAME}
  strategy:
    rollingUpdate:
      maxSurge: 50%
      maxUnavailable: 50%
    type: RollingUpdate
  template:
    metadata:
      labels:
        workload.user.cattle.io/workloadselector: apps.deployment-dev-${K8S_RESOURCE_NAME}
    spec:
      affinity: {}
      containers:
      - envFrom:
        - configMapRef:
            name: contentful-proxy-cache-env
            optional: false
        image: ${DOCKER_IMAGE_TAG}
        imagePullPolicy: Always
        name: api-proxy-cache-web
        ports:
        - containerPort: 8080
          name: 8080tcp
          protocol: TCP
        readinessProbe:
          failureThreshold: 3
          httpGet:
            path: /
            port: 8080
            scheme: HTTP
          periodSeconds: 10
          successThreshold: 1
          timeoutSeconds: 1
        resources:
          limits:
            cpu: 100m
            memory: 128Mi
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
