# Cloud Foundry manifest
---
buildpack: nodejs_buildpack
command: NODE_ENV=production cservice --restartOnMemUsage 134217728 --cli false index.js
memory: 512M
health-check-type: process
stack: cflinuxfs3
env:
  HOST: 0.0.0.0
  OPTIMIZE_MEMORY: true
